site_name: Unofficial Eskom
site_url: 'https://unofficialeskom.com'
site_description: >-
    Stats and information about Eskom, South Africa's electricity provider. Not endorsed or official.

theme:
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png

  palette:
    primary: blue 

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - meta

nav:
  - Home: index.md
  - Dashboards: 
      - dashboards/index.md
      - Long-term Dashboards: dashboards/long-term.md
  - Heatmap: heatmap/index.md
  - FAQ: faq/index.md
  - Latest: latest/index.md
  - About: about/index.md
extra:
  generator: false
  analytics:
    provider: plausible 
    property: unofficialeskom.com
